# Generated by Django 5.2.6 on 2025-09-28 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CpdInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('type_course', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('date_start', models.DateField()),
                ('date_complete', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(max_length=10, null=True)),
                ('grade', models.CharField(max_length=45, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
